version: '3.9'
services:
  RetrieveAgeUF:
    build: ./UFs/Age
    image: uf-age
    ports:
      - "8001:8080"

  MeasureBloodPressureUF:
    build: ./UFs/BloodPressure
    image: uf-bloodpressure
    ports:
      - "8002:8080"

  CheckChronicIllnessUF:
    build: ./UFs/ChronicIllness
    image: uf-chronicillness
    ports:
      - "8003:8080"

  DummyActionUF:
    build: ./UFs/DummyAction
    image: uf-dummyaction
    ports:
      - "8004:8080"

  MeasureHeartRateUF:
    build: ./UFs/HeartRate
    image: uf-heartrate
    ports:
      - "8005:8080"

  EvaluateImmuneCompromisationUF:
    build: ./UFs/ImmuneCompromisation
    image: uf-immunecompromisation
    ports:
      - "8006:8080"

  MeasureMeanArterialPressureUF:
    build: ./UFs/MeanArterialPressure
    image: uf-map
    ports:
      - "8007:8080"

  MeasureRespirationRateUF:
    build: ./UFs/RespirationRate
    image: uf-respirationrate
    ports:
      - "8008:8080"

  CheckSurgeryHistoryUF:
    build: ./UFs/SurgeryHistory
    image: uf-surgeryhistory
    ports:
      - "8009:8080"

  MeasureSystolicBloodPressureUF:
    build: ./UFs/SystolicBloodPressure
    image: uf-sbp
    ports:
      - "8010:8080"

  MeasureTempertureUF:
    build: ./UFs/Temperature
    image: uf-temperature
    ports:
      - "8011:8080"

  PatientMedicalRecordAdaptor:
    build: ./Adaptors/PatientMedicalRecordAdaptor
    image: patient-medical-record-adaptor
    ports:
      - "8012:8080"


  PatientMonitorType1:
    build: ./Adaptors/PatientMonitorAdaptorType1
    image: patient-monitor-adaptor-type-1
    ports:
      - "8013:8080"

  PatientMonitorType2:
    build: ./Adaptors/PatientMonitorAdaptorType2
    image: patient-monitor-adaptor-type-2
    ports:
      - "8014:8080"

  WorkflowRequestControllerUF:
    build: ./UFs/WorkflowRequestController
    image: workflow-request-controller
    ports:
      - "8015:8080"
