version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: patient_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql



